
test_001
Traceback (most recent call last):
  File "D:\xiong\hello_world\test_001.py", line 24, in test_001
    a=1/0
ZeroDivisionError: division by zero

test_002
Traceback (most recent call last):
  File "D:\xiong\hello_world\test_001.py", line 31, in test_002
    b=1+a
NameError: name 'a' is not defined
